### ISSUE TITLE
UBC PowerPoint templates

### ISSUE THREAD

**Issue by firasm** [apreshill/ppt-templates#1]
Hello,

Saw your post on Twitter and thought I’d contribute my institutional PowerPoint templates:

- https://assets.brand.ubc.ca/downloads/ubc_photo_ppt_arial.zip
- https://assets.brand.ubc.ca/downloads/ubc_text_ppt_arial.zip

The above links include 4:3 and 16:9 versions of the template. 

Thanks!

**Comment by apreshill** [comment]
Thank you!
